export default {
  async fetch(request, env) {
    try {
      const url = new URL(request.url);
      const cord1 = url.searchParams.get("cord1");
      const cord2 = url.searchParams.get("cord2");
      const temp = url.searchParams.get("temp");
      const type = url.searchParams.get("type");

      //Temperature thresholds
      const nearDeadlyTemp = 90;
      const deadlyThreshold = 95;
      let msg = '';

      if (!cord1 || !cord2 || !temp) {
        return new Response("Missing parameters", { status: 400 });
      }

      const accountSid = env.TWILIO_SID;
      const authToken = env.TWILIO_AUTH;
      const fromNumber = env.TWILIO_FROM;
      let toNumber = '';

      if (!accountSid || !authToken || !fromNumber) {
        return new Response("Missing Twilio environment variables", { status: 500 });
      }

      if (temp > deadlyThreshold && type == 'gen') {
          msg += 'EMERGENCY: Deadly vehicle temperature is detected while infant is present. Immediate action is required. Please remove and cool the child.\nCurrent temperature: ' + temp + 'F.\nVehicle location: https://www.google.com/maps/search/?api=1&query=' + cord1 + ',' + cord2 + '\n EMERGENCY SERVICE HAVE BEEN CONTACTED. If you think this is a mistake, temporarily disarm the system by pressing the reset button on the device.';
          toNumber = '+12405619161';
      } else if (temp > deadlyThreshold && type == 'emg') {
          msg += 'AUTOMATED EMERGENCY ALERT: A child has been detected unsupervised in a vehicle with deadly temperatures of ' + temp + 'F.\nVehicle Info: Gray TOYOTA Camry\nPlate: XXXX-XXXX\nVehicle location: ' + cord1 + ',' + cord2 + '\n Parent has been notified though not confirmed whether they have received the message nor taken action to remove the child from the vehicle.\nNOTE: This is an automated message generated by InfantGuard.';
          toNumber = '+12405619161';
      } else if (temp > nearDeadlyTemp && type == 'gen') {
          msg += 'EMERGENCY: High vehicle temperature is detected while infant is present. Please take action to remove the child and ensure their safety.\nCurrent temperature: ' + temp + 'F.\nVehicle location: https://www.google.com/maps/search/?api=1&query=' + cord1 + ',' + cord2 + '\n Emergency services will be notified if temperatures reach' + deadlyThreshold + 'F. If you think this is a mistake, temporarily disarm the system by pressing the reset button on the device.';
          toNumber = '+12405619161';
      } else if (type == 'gen') {
          msg += 'ALERT: Infant left unsupervised in vehicle. Please take immediate action to ensure the safety of the child.\nVehicle location: https://www.google.com/maps/search/?api=1&query=' + cord1 + ',' + cord2 + '\n If you think this is a mistake, temporarily disarm the system by pressing the reset button on the device.';
          toNumber = '+12405619161';
      } else if (type == 'stat' && temp == 1000) {
          msg += 'InfantGuard system has been temporarily disarmed for 15 minutes. InfantGuard will not be monitoring the vehicle during this period.';
          toNumber = '+12405619161';
      } else if (type == 'stat' && temp == 2000) {
          msg += 'InfantGuard system has been reactivated and is now monitoring the vehicle.';
          toNumber = '+12405619161';
      } else if (type == 'stat' && temp == 0) {
          msg += 'InfantGuard has been turned on and is now monitoring the vehicle.';
          toNumber = '+12405619161';
      }
      const twilioUrl = `https://api.twilio.com/2010-04-01/Accounts/${accountSid}/Messages.json`;

      const body = new URLSearchParams({
        To: toNumber,
        From: fromNumber,
        Body: msg,
      });

      const auth = btoa(`${accountSid}:${authToken}`);

      const res = await fetch(twilioUrl, {
        method: "POST",
        headers: {
          Authorization: `Basic ${auth}`,
          "Content-Type": "application/x-www-form-urlencoded",
        },
        body: body.toString(),
      });

      const text = await res.text();
      return new Response(text, {
        status: res.status,
        headers: { "Access-Control-Allow-Origin": "*" },
      });
    } catch (err) {
      return new Response(`Worker error: ${err.message}`, { status: 500 });
    }
  },
};
